package new

var fullStoreGo = `package store

import (
	"github.com/gascore/gas/std/store"
)

var S *store.Store

func InitStore() error {
	var err error
	S, err = store.New(&store.Store{
		Data: map[string]interface{}{
			"hello": "Hello world!",
			"count": 0,
		},
	})
	if err != nil {
		return err
	}

	return nil
}`

var fullAboutGas = `<template>
    <div id="about">
        <h1>
			This project generated by 
			<a href="https://github.com/gascore/gas/gasx">gasx</a>
        </h1>
    </div>
</template>

<script>
package components

import (
    r "github.com/gascore/gas/std/router"
    . "your_project_path/store"
    "github.com/gascore/gas"
)

func About(info r.RouteInfo) *gas.Component {
    return S.RC(gas.NC(
        &gas.C{
        },
        aboutT,), nil)
}

var aboutT gas.GetComponentChildes
</script>`

var fullHelloGas = `<template>
	<div id="home">
		<h1>
			{{ S.Get("hello").(string) }}
		</h1>
	</div>
</template>

<script>
package components

import (
	"github.com/gascore/gas"
	r "github.com/gascore/gas/std/router"
	 . "your_project_path/store"
)

func Hello(info r.RouteInfo) *gas.Component {
	return S.RC(gas.NC(
		&gas.C{
		},
		helloT,), nil)
}

var helloT gas.GetComponentChildes
</script>
`

var fullMainGas = `<template>
    <div>
        <header class="navbar bdb(1px,solid,#dedede) mb(12px)">
            <section class="navbar-section">
                <span class="navbar-brand mr-2">
                    Hello world!
                </span>
                <span class="btn btn-link">
                    <e run="r.LinkStatic(` + "`/`" + `, false, ctx)">
                        Home
                    </e>
                </span>
                <span class="btn btn-link">
                    <e run="r.LinkStatic(` + "`/about`" + `, false, ctx)">
                        About
                    </e>
                </span>
            </section>
        </header>

		<div>
			<e run="r.InitRouter(ctx)" />
		</div>

		<footer>
            Created by
            <a href="https://your.site/" target="_blank">
                Your name
            </a>
            with
            <a href="https://github.com/gascore/gas" target="_blank">
                gas
            </a>,
            <a href="https://github.com/gascore/gas/gasx" target="_blank">
                gasx
            </a>,
            <a href="https://github.com/gascore/gas/std/router" target="_blank">
                gas-router
            </a>,
            <a href="https://github.com/gascore/gas/std/store" target="_blank">
                gas-store
            </a>
            and love
        </footer>
	</div>
</template>

<script>
package main

import (
	"github.com/gascore/gas"
	"github.com/gascore/gas/web"

	. "your_project_path/store"
	r "github.com/gascore/gas/std/router"
)

func link(to string, replace bool, body gas.External) *gas.Component {
	return r.LinkStatic(to, replace, ctx, body)
}

func main() {
	err := InitStore()
	must(err)

    app, err :=
        gas.New(
            web.GetBackEnd(),
            "app",
            &gas.Component{},
            mainT,)
    must(err)

    err = gas.Init(app)
    must(err)
    web.KeepAlive()
}

func must(err error) {
    if err != nil {
        panic(err)
    }
}

var mainT gas.GetComponentChildes
</script>` + mainCss
