package new

var routerMainGas = `<template>
    <div>
        <header class="navbar bdb(1px,solid,#dedede) mb(12px)">
            <section class="navbar-section">
                <span class="navbar-brand mr-2">
                    Hello world!
                </span>
                <span class="btn btn-link">
                    <e run="r.LinkStatic(` + "`/`" + `, false, ctx)">
                        Home
                    </e>
                </span>
                <span class="btn btn-link">
                    <e run="r.LinkStatic(` + "`/about`" + `, false, ctx)">
                        About
                    </e>
                </span>
            </section>
        </header>

		<div>
			<e run="r.InitRouter(ctx)" />
		</div>

		<footer>
            Created by
            <a href="https://your.site/" target="_blank">
                Your name
            </a>
            with
            <a href="https://github.com/gascore/gas" target="_blank">
                gas
            </a>,
            <a href="https://github.com/gascore/gas/gasx" target="_blank">
                gasx
            </a>,
            <a href="https://github.com/gascore/gas/std/router" target="_blank">
                gas-router
            </a>
            and love
        </footer>
	</div>
</template>

<script>
package main

import (
	"github.com/gascore/gas"
	"github.com/gascore/gas/web"

	r "github.com/gascore/gas/std/router"
)

func link(to string, replace bool, body gas.External) *gas.Component {
	return r.LinkStatic(to, replace, ctx, body)
}

func main() {
    app, err :=
        gas.New(
            web.GetBackEnd(),
            "app",
            &gas.Component{},
            mainT,)
    must(err)

    err = gas.Init(app)
    must(err)
    web.KeepAlive()
}

func must(err error) {
    if err != nil {
        panic(err)
    }
}

var mainT gas.GetComponentChildes
</script>` + mainCss

var routerHelloGas = `<template>
	<div id="home">
		<h1>
			{{ this.Get("hello").(string) }}
		</h1>
	</div>
</template>

<script>
package components

import (
	"github.com/gascore/gas"
	r "github.com/gascore/gas/std/router"
)

func Hello(info r.RouteInfo) *gas.Component {
	return gas.NC(
		&gas.C{
			Data: map[string]interface{} {
				"hello": "Hello world!",
			},
		},
		helloT,)
}

var helloT gas.GetComponentChildes
</script>
`

var routerAboutGas = `<template>
    <div id="about">
        <h1>
			This project generated by 
			<a href="https://github.com/gascore/gas/gasx">gasx</a>
        </h1>
    </div>
</template>

<script>
package components

import (
    r "github.com/gascore/gas/std/router"
    "github.com/gascore/gas"
)

func About(info r.RouteInfo) *gas.Component {
    return gas.NC(
        &gas.C{
        },
        aboutT,)
}

var aboutT gas.GetComponentChildes
</script>`

var routesGo = `package main

import (
	r "github.com/gascore/gas/std/router"
	c "your_project_path/components"
)

var ctx = &r.Ctx{
	Routes: []r.Route{
		{
			Name:      "home",
			Component: c.Hello,
			Path:      "/",
			Exact:     true,
		},
		{
			Name:      "about",
			Component: c.About,
			Path:      "/about",
			Exact:     true,
		},
	},

	Settings: r.Settings{
		HashMode: true,
		GetUserConfirmation: func() bool {
			return false
		},
		ForceRefresh: !r.SupportHistory(),
	},
}`
